from pathlib import Path
from xml.sax.saxutils import escape


# =========================================================
# Paths
# =========================================================

ROOT = Path(__file__).resolve().parent.parent

INPUT = ROOT / "assets" / "portrait" / "portrait.txt"
OUTPUT = ROOT / "assets" / "portrait" / "portrait.svg"


# =========================================================
# Configuration
# =========================================================

# Matches the 90-column portrait generated by portrait.py.
COLUMNS = 90

# SVG display size.
DISPLAY_WIDTH = 700

# Monospace typography.
FONT_FAMILY = (
    "DejaVu Sans Mono, "
    "Liberation Mono, "
    "Courier New, "
    "monospace"
)

FONT_SIZE = 16

# Approximate monospace character metrics.
CHAR_WIDTH = 9.6
LINE_HEIGHT = 17

# Padding around portrait.
PADDING_X = 20
PADDING_Y = 20

# GitHub-style dark background.
BACKGROUND = "#0d1117"

# ASCII color.
TEXT_COLOR = "#c9d1d9"

# Animation.
ROW_DELAY = 0.055
ROW_DURATION = 0.45


# =========================================================
# Read portrait
# =========================================================

def read_portrait():
    if not INPUT.exists():
        raise FileNotFoundError(
            f"Portrait file not found:\n{INPUT}"
        )

    # IMPORTANT:
    #
    # Do NOT strip spaces.
    #
    # Leading spaces are part of the portrait geometry.
    #
    return INPUT.read_text(
        encoding="utf-8"
    ).splitlines()


# =========================================================
# Escape text safely for XML
# =========================================================

def svg_text(value):
    return escape(
        value,
        {
            '"': "&quot;",
            "'": "&apos;",
        }
    )


# =========================================================
# Generate SVG
# =========================================================

def generate_svg(rows):

    if not rows:
        raise ValueError(
            "portrait.txt contains no rows."
        )

    # -----------------------------------------------------
    # Preserve the actual portrait width.
    # -----------------------------------------------------

    max_columns = max(
        len(row)
        for row in rows
    )

    # Force the known portrait width.
    max_columns = max(
        max_columns,
        COLUMNS
    )

    row_count = len(rows)

    content_width = (
        max_columns * CHAR_WIDTH
    )

    content_height = (
        row_count * LINE_HEIGHT
    )

    canvas_width = (
        content_width
        + PADDING_X * 2
    )

    canvas_height = (
        content_height
        + PADDING_Y * 2
    )

    svg = []

    # =====================================================
    # Header
    # =====================================================

    svg.append(
        f'''<?xml version="1.0" encoding="UTF-8"?>
<svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width="{DISPLAY_WIDTH}"
    viewBox="0 0 {canvas_width:.2f} {canvas_height:.2f}"
    preserveAspectRatio="xMinYMin meet"
    role="img"
    aria-label="Animated ASCII portrait"
>

'''
    )

    # =====================================================
    # Background
    # =====================================================

    svg.append(
        f'''    <rect
        x="0"
        y="0"
        width="{canvas_width:.2f}"
        height="{canvas_height:.2f}"
        fill="{BACKGROUND}"
    />

'''
    )

    # =====================================================
    # Font
    # =====================================================

    svg.append(
        f'''    <style>
        .portrait {{
            font-family: {FONT_FAMILY};
            font-size: {FONT_SIZE}px;
            font-weight: 400;
            letter-spacing: 0;
            white-space: pre;
        }}
    </style>

'''
    )

    # =====================================================
    # Animation clips
    # =====================================================

    svg.append("    <defs>\n")

    for i, row in enumerate(rows):

        # Use character count rather than relying on browser
        # font measurement.
        row_width = max(
            CHAR_WIDTH,
            len(row) * CHAR_WIDTH
        )

        y = (
            PADDING_Y
            + (i + 1) * LINE_HEIGHT
        )

        svg.append(
            f'''        <clipPath id="row-{i}">
            <rect
                x="{PADDING_X}"
                y="{y - FONT_SIZE:.2f}"
                width="0"
                height="{LINE_HEIGHT * 1.25:.2f}"
            >
                <animate
                    attributeName="width"
                    from="0"
                    to="{row_width:.2f}"
                    begin="{i * ROW_DELAY:.3f}s"
                    dur="{ROW_DURATION:.3f}s"
                    fill="freeze"
                />
            </rect>
        </clipPath>
'''
        )

    svg.append(
        "    </defs>\n\n"
    )

    # =====================================================
    # Portrait text
    # =====================================================

    svg.append(
        f'''    <g
        class="portrait"
        fill="{TEXT_COLOR}"
        xml:space="preserve"
    >
'''
    )

    for i, row in enumerate(rows):

        y = (
            PADDING_Y
            + (i + 1) * LINE_HEIGHT
        )

        # -------------------------------------------------
        # IMPORTANT:
        #
        # Each row is rendered as its own <text>.
        #
        # xml:space="preserve" prevents leading spaces from
        # being collapsed.
        #
        # textLength forces the browser to maintain the
        # intended monospace geometry.
        # -------------------------------------------------

        row_width = max(
            CHAR_WIDTH,
            len(row) * CHAR_WIDTH
        )

        svg.append(
            f'''        <text
            x="{PADDING_X}"
            y="{y:.2f}"
            xml:space="preserve"
            textLength="{row_width:.2f}"
            lengthAdjust="spacing"
            clip-path="url(#row-{i})"
        >{svg_text(row)}</text>
'''
        )

    svg.append(
        "    </g>\n\n"
    )

    # =====================================================
    # Cursor
    # =====================================================

    svg.append(
        f'''    <g
        fill="{TEXT_COLOR}"
        pointer-events="none"
    >
'''
    )

    for i, row in enumerate(rows):

        row_width = max(
            CHAR_WIDTH,
            len(row) * CHAR_WIDTH
        )

        y = (
            PADDING_Y
            + i * LINE_HEIGHT
        )

        begin = (
            i * ROW_DELAY
        )

        svg.append(
            f'''        <rect
            x="{PADDING_X}"
            y="{y:.2f}"
            width="1.5"
            height="{LINE_HEIGHT:.2f}"
            opacity="0"
        >
            <animate
                attributeName="x"
                from="{PADDING_X}"
                to="{PADDING_X + row_width:.2f}"
                begin="{begin:.3f}s"
                dur="{ROW_DURATION:.3f}s"
                fill="freeze"
            />

            <animate
                attributeName="opacity"
                values="0;1;1;0"
                keyTimes="0;0.05;0.90;1"
                begin="{begin:.3f}s"
                dur="{ROW_DURATION:.3f}s"
                fill="freeze"
            />
        </rect>
'''
        )

    svg.append(
        "    </g>\n"
    )

    # =====================================================
    # Footer
    # =====================================================

    svg.append(
        "</svg>\n"
    )

    return "".join(svg)


# =========================================================
# Main
# =========================================================

def main():

    print()
    print("=" * 60)
    print("GENERATING FINAL ASCII PORTRAIT SVG")
    print("=" * 60)
    print()

    rows = read_portrait()

    svg = generate_svg(rows)

    OUTPUT.write_text(
        svg,
        encoding="utf-8"
    )

    print(f"Rows:           {len(rows)}")
    print(f"Characters:     {max(map(len, rows))}")
    print(f"Font size:      {FONT_SIZE}px")
    print(f"Character width:{CHAR_WIDTH}px")
    print(f"Display width:  {DISPLAY_WIDTH}px")
    print(f"Row delay:      {ROW_DELAY}s")
    print(f"Row duration:   {ROW_DURATION}s")
    print()
    print("Output:")
    print(OUTPUT)
    print()
    print("=" * 60)


if __name__ == "__main__":
    main()